import type { Metadata } from "next"
import { ReactNode } from "react"
import { Inter } from "next/font/google"
import { Toaster } from "@/components/ui/toaster"
import ConvexClientProvider from "./ConvexClientProvider"
import Header from "./header"
import Footer from "./footer"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>
          <Toaster />
          <Header />
          {children}
          <Footer />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
